<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\tModLoader.targets" />

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <NoWarn>1701;1702;649</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <NoWarn>1701;1702;649</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Transoceanic\Transoceanic.csproj" />
        <ProjectReference Include="..\TransoceanicCodeAssist\TransoceanicCodeAssist.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="CalamityMod">
        <HintPath>..\..\CalamityMod\CalamityMod.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Visuals\BossBar\Textures\Retro\" />
    </ItemGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="call $(ProjectDir)PreBuild\EasyXnb\EasyXnb.exe" />
    </Target>

</Project>