// Developed by ColdsUx

namespace TransoceanicCodeAssist;

/// <summary>
/// 为 Transoceanic 系列源生成器提供通用辅助方法、常量和扩展。
/// 该类型中的所有成员均为静态成员，可在源生成器的初始化与执行阶段复用。
/// </summary>
internal static class SourceGeneratorHelper
{
    /// <summary>
    /// 标准文件头。包含自动生成标识、开发者说明、必要的警告禁用等。
    /// </summary>
    public const string FileHeader =
    """
        // <auto-generated/>
        // Developed by ColdsUx

        #pragma warning disable CS0106
        #pragma warning disable CS0109
        #pragma warning disable CS1591

        """;

    /// <summary>
    /// 用于标记永远不会出现在编辑器浏览列表中的特性字符串。
    /// 等价于 <c>[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]</c>。
    /// </summary>
    public const string NeverBrowsableIdentifier = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    /// <summary>
    /// 外部特性命名空间的前缀，便于在生成的代码中统一引用。
    /// 例如：<c>global::Transoceanic.Framework.ExternalAttributes.SomeAttribute</c>。
    /// </summary>
    public const string ExternalAttributePrefix = "global::Transoceanic.Framework.ExternalAttributes.";

    /// <summary>
    /// 当前代码辅助库的版本号，主要用于 <see cref="GetGeneratedCodeMarker"/> 生成的标记特性。
    /// </summary>
    public const string Version = "1.0.0.0";

    /// <summary>
    /// 生成一个带有 <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute"/> 特性的字符串，
    /// 用于标记生成的代码来自指定的源生成器。
    /// </summary>
    /// <param name="generatorName">源生成器的名称，会拼接到特性构造函数参数的 "TransoceanicCodeAssist." 之后。</param>
    /// <returns>格式化的特性字符串，例如：<c>[global::System.CodeDom.Compiler.GeneratedCode("TransoceanicCodeAssist.MyGen", "1.0.0.0")]</c>。</returns>
    public static string GetGeneratedCodeMarker(string generatorName) => $"""[global::System.CodeDom.Compiler.GeneratedCode("TransoceanicCodeAssist.{generatorName}", "{Version}")]""";

    /// <summary>
    /// 获取解决方案中所有类型声明语法的增量值提供程序。
    /// 可用于后续筛选出 <see langword="partial"/> 类型等。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <returns>提供 <see cref="Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax"/> 节点的增量值序列。</returns>
    public static IncrementalValuesProvider<TypeDeclarationSyntax> GetTypeDeclarations(IncrementalGeneratorInitializationContext context) =>
        context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is TypeDeclarationSyntax,
            transform: (ctx, _) => (TypeDeclarationSyntax)ctx.Node
        );

    /// <summary>
    /// 尝试从类型声明语法和编译的组合中获取 <see cref="INamedTypeSymbol"/>，要求该类型声明包含 <see langword="partial"/> 关键字。
    /// </summary>
    /// <param name="tuple">包含类型声明语法（左）和编译（右）的元组。</param>
    /// <param name="symbol">当方法返回 <see langword="true"/> 时，表示找到的命名类型符号；否则为 <see langword="null"/>。</param>
    /// <returns>如果类型声明是分部类型且能获取到符号，则返回 <see langword="true"/>；否则返回 <see langword="false"/>。</returns>
    public static bool TryGetPartialTypeSymbolInfo((TypeDeclarationSyntax Left, Compilation Right) tuple, out INamedTypeSymbol symbol)
    {
        TypeDeclarationSyntax typeDecl = tuple.Left;
        Compilation compilation = tuple.Right;

        if (typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            SemanticModel model = compilation.GetSemanticModel(typeDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(typeDecl) is INamedTypeSymbol typeSymbol)
            {
                symbol = typeSymbol;
                return true;
            }
        }

        symbol = null;
        return false;
    }

    /// <summary>
    /// 获取解决方案中所有方法声明语法的增量值提供程序。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <returns>提供 <see cref="Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax"/> 节点的增量值序列。</returns>
    public static IncrementalValuesProvider<MethodDeclarationSyntax> GetMethodDeclarations(IncrementalGeneratorInitializationContext context) =>
        context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is MethodDeclarationSyntax,
            transform: (ctx, _) => (MethodDeclarationSyntax)ctx.Node
        );

    /// <summary>
    /// 尝试从方法声明语法和编译的组合中获取 <see cref="IMethodSymbol"/>，要求该方法声明包含 <see langword="partial"/> 关键字。
    /// </summary>
    /// <param name="tuple">包含方法声明语法（左）和编译（右）的元组。</param>
    /// <param name="symbol">当方法返回 <see langword="true"/> 时，表示找到的方法符号；否则为 <see langword="null"/>。</param>
    /// <returns>如果方法声明是分部方法且能获取到符号，则返回 <see langword="true"/>；否则返回 <see langword="false"/>。</returns>
    public static bool TryGetPartialMethodSymbolInfo((MethodDeclarationSyntax Left, Compilation Right) tuple, out IMethodSymbol symbol)
    {
        MethodDeclarationSyntax methodDecl = tuple.Left;
        Compilation compilation = tuple.Right;

        if (methodDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            SemanticModel model = compilation.GetSemanticModel(methodDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(methodDecl) is IMethodSymbol methodSymbol)
            {
                symbol = methodSymbol;
                return true;
            }
        }

        symbol = null;
        return false;
    }

    /// <summary>
    /// 获取解决方案中所有属性声明语法的增量值提供程序。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <returns>提供 <see cref="Microsoft.CodeAnalysis.CSharp.Syntax.PropertyDeclarationSyntax"/> 节点的增量值序列。</returns>
    public static IncrementalValuesProvider<PropertyDeclarationSyntax> GetPropertyDeclarations(IncrementalGeneratorInitializationContext context) =>
    context.SyntaxProvider.CreateSyntaxProvider(
        predicate: (node, _) => node is PropertyDeclarationSyntax,
        transform: (ctx, _) => (PropertyDeclarationSyntax)ctx.Node
    );

    /// <summary>
    /// 尝试从属性声明语法和编译的组合中获取 <see cref="IPropertySymbol"/>，要求该属性声明包含 <see langword="partial"/> 关键字。
    /// </summary>
    /// <param name="tuple">包含属性声明语法（左）和编译（右）的元组。</param>
    /// <param name="symbol">当方法返回 <see langword="true"/> 时，表示找到的属性符号；否则为 <see langword="null"/>。</param>
    /// <returns>如果属性声明是分部属性且能获取到符号，则返回 <see langword="true"/>；否则返回 <see langword="false"/>。</returns>
    public static bool TryGetPartialPropertySymbolInfo((PropertyDeclarationSyntax Left, Compilation Right) tuple, out IPropertySymbol symbol)
    {
        PropertyDeclarationSyntax property = tuple.Left;
        Compilation compilation = tuple.Right;

        if (property.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            SemanticModel model = compilation.GetSemanticModel(property.SyntaxTree);
            if (model.GetDeclaredSymbol(property) is IPropertySymbol propertySymbol)
            {
                symbol = propertySymbol;
                return true;
            }
        }

        symbol = null;
        return false;
    }

    /// <summary>
    /// 获取类型符号信息的增量值提供程序，通过工厂函数将 <see cref="INamedTypeSymbol"/> 和编译转换为自定义信息对象。
    /// 自动过滤掉非分部类型以及无效的信息。
    /// </summary>
    /// <typeparam name="TInfo">信息对象类型，必须继承自 <see cref="TypeSymbolInfoBase"/>。</typeparam>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <param name="factory">用于从符号和编译创建 <typeparamref name="TInfo"/> 实例的工厂委托。若为 <see langword="null"/> 则返回默认的空提供程序。</param>
    /// <returns>提供有效类型信息的增量值序列。</returns>
    public static IncrementalValuesProvider<TInfo> GetTypeInfos<TInfo>(IncrementalGeneratorInitializationContext context, Func<INamedTypeSymbol, Compilation, TInfo> factory) where TInfo : TypeSymbolInfoBase
    {
        if (factory is null)
            return default;

        return GetTypeDeclarations(context).Combine(context.CompilationProvider)
            .Select((tuple, _) =>
            {
                if (!TryGetPartialTypeSymbolInfo(tuple, out INamedTypeSymbol symbol))
                    return null;
                TInfo info = factory(symbol, tuple.Right.WithAllMetadata());
                if (!info.Valid)
                    return null;
                return info;
            }).Where(info => info is not null);
    }

    /// <summary>
    /// 收集所有有效的类型符号信息，并以不可变数组的形式提供。
    /// </summary>
    /// <typeparam name="TInfo">信息对象类型，必须继承自 <see cref="TypeSymbolInfoBase"/>。</typeparam>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <param name="factory">创建信息对象的工厂委托。</param>
    /// <returns>提供所有有效类型信息数组的增量值。</returns>
    public static IncrementalValueProvider<ImmutableArray<TInfo>> GetCollectedTypeInfos<TInfo>(IncrementalGeneratorInitializationContext context, Func<INamedTypeSymbol, Compilation, TInfo> factory) where TInfo : TypeSymbolInfoBase =>
        GetTypeInfos(context, factory).Collect();

    /// <summary>
    /// 获取方法符号信息的增量值提供程序，通过工厂函数将 <see cref="IMethodSymbol"/> 和编译转换为自定义信息对象。
    /// 自动过滤掉非分部方法以及无效的信息。
    /// </summary>
    /// <typeparam name="TInfo">信息对象类型，必须继承自 <see cref="MethodSymbolInfoBase"/>。</typeparam>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <param name="factory">用于从符号和编译创建 <typeparamref name="TInfo"/> 实例的工厂委托。</param>
    /// <returns>提供有效方法信息的增量值序列。</returns>
    public static IncrementalValuesProvider<TInfo> GetMethodInfos<TInfo>(IncrementalGeneratorInitializationContext context, Func<IMethodSymbol, Compilation, TInfo> factory) where TInfo : MethodSymbolInfoBase
    {
        if (factory is null)
            return default;

        return GetMethodDeclarations(context).Combine(context.CompilationProvider)
            .Select((tuple, _) =>
            {
                if (!TryGetPartialMethodSymbolInfo(tuple, out IMethodSymbol symbol))
                    return null;
                TInfo info = factory(symbol, tuple.Right.WithAllMetadata());
                if (!info.Valid)
                    return null;
                return info;
            }).Where(info => info is not null);
    }

    /// <summary>
    /// 收集所有有效的方法符号信息，并以不可变数组的形式提供。
    /// </summary>
    /// <typeparam name="TInfo">信息对象类型，必须继承自 <see cref="MethodSymbolInfoBase"/>。</typeparam>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <param name="factory">创建信息对象的工厂委托。</param>
    /// <returns>提供所有有效方法信息数组的增量值。</returns>
    public static IncrementalValueProvider<ImmutableArray<TInfo>> GetCollectedMethodInfos<TInfo>(IncrementalGeneratorInitializationContext context, Func<IMethodSymbol, Compilation, TInfo> factory) where TInfo : MethodSymbolInfoBase =>
        GetMethodInfos(context, factory).Collect();

    /// <summary>
    /// 获取属性符号信息的增量值提供程序，通过工厂函数将 <see cref="IPropertySymbol"/> 和编译转换为自定义信息对象。
    /// 自动过滤掉非分部属性以及无效的信息。
    /// </summary>
    /// <typeparam name="TInfo">信息对象类型，必须继承自 <see cref="PropertySymbolInfoBase"/>。</typeparam>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <param name="factory">用于从符号和编译创建 <typeparamref name="TInfo"/> 实例的工厂委托。</param>
    /// <returns>提供有效属性信息的增量值序列。</returns>
    public static IncrementalValuesProvider<TInfo> GetPropertyInfos<TInfo>(IncrementalGeneratorInitializationContext context, Func<IPropertySymbol, Compilation, TInfo> factory) where TInfo : PropertySymbolInfoBase
    {
        if (factory is null)
            return default;

        return GetPropertyDeclarations(context).Combine(context.CompilationProvider)
            .Select((tuple, _) =>
            {
                if (!TryGetPartialPropertySymbolInfo(tuple, out IPropertySymbol symbol))
                    return null;
                TInfo info = factory(symbol, tuple.Right.WithAllMetadata());
                if (!info.Valid)
                    return null;
                return info;
            }).Where(info => info is not null);
    }

    /// <summary>
    /// 收集所有有效的属性符号信息，并以不可变数组的形式提供。
    /// </summary>
    /// <typeparam name="TInfo">信息对象类型，必须继承自 <see cref="PropertySymbolInfoBase"/>。</typeparam>
    /// <param name="context">增量生成器初始化上下文。</param>
    /// <param name="factory">创建信息对象的工厂委托。</param>
    /// <returns>提供所有有效属性信息数组的增量值。</returns>
    public static IncrementalValueProvider<ImmutableArray<TInfo>> GetCollectedPropertyInfos<TInfo>(IncrementalGeneratorInitializationContext context, Func<IPropertySymbol, Compilation, TInfo> factory) where TInfo : PropertySymbolInfoBase =>
        GetPropertyInfos(context, factory).Collect();

    /// <summary>
    /// 在给定的特性数据集合中查找完全限定名匹配的特性。
    /// 会自动将传入的 <paramref name="attributeFullName"/> 中的嵌套类型分隔符 '+' 替换为 '.'，
    /// 以与 Roslyn 的显示格式保持一致。
    /// </summary>
    /// <param name="attributeFullName">特性的完全限定名，例如 "global::Namespace.Outer.InnerAttribute"。</param>
    /// <param name="datas">待搜索的特性数据数组。</param>
    /// <param name="data">当方法返回 <see langword="true"/> 时，为匹配的 <see cref="AttributeData"/>；否则为 <see langword="null"/>。</param>
    /// <returns>如果找到匹配的特性，则返回 <see langword="true"/>；否则返回 <see langword="false"/>。</returns>
    public static bool TryGetAttribute(string attributeFullName, AttributeData[] datas, out AttributeData data)
    {
        //将传入的完全限定名中的嵌套类型分隔符 '+' 替换为 '.'（与 Roslyn 的显示格式一致）
        string targetFullName = attributeFullName.Replace('+', '.');

        data = datas.FirstOrDefault(a =>
        {
            if (a.AttributeClass is null)
                return false;

            //获取特性类的完全限定名（如 "global::Namespace.Outer.InnerAttribute"）
            string attributeFullName = a.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return attributeFullName == targetFullName;
        });

        return data is not null;
    }

    #region 扩展

    /// <summary>
    /// 为 <see cref="Compilation"/> 提供扩展方法。
    /// </summary>
    extension(Compilation compilation)
    {
        /// <summary>
        /// 返回一个新的编译对象，其元数据导入选项设置为 <see cref="MetadataImportOptions.All"/>，
        /// 确保在语义分析时能够访问所有元数据（包括内部成员）。
        /// </summary>
        /// <returns>修改了元数据导入选项后的编译对象。</returns>
        public Compilation WithAllMetadata()
        {
            if (compilation.Options is CSharpCompilationOptions originalOptions)
            {
                CSharpCompilationOptions newOptions = originalOptions.WithMetadataImportOptions(MetadataImportOptions.All);
                return compilation.WithOptions(newOptions);
            }

            return compilation;
        }
    }

    /// <summary>
    /// 为 <see cref="ITypeSymbol"/> 提供扩展成员，便于获取更精确的完全限定名称和显示字符串。
    /// </summary>
    extension(ITypeSymbol typeSymbol)
    {
        /// <summary>
        /// 获取类型的完整元数据名称，包含命名空间和嵌套类型的 “+” 分隔符。
        /// 例如：<c>Namespace.OuterType+InnerType</c>。
        /// </summary>
        public string FullMetadataName
        {
            get
            {
                if (typeSymbol.ContainingType is not null)
                    return typeSymbol.ContainingType.FullMetadataName + "+" + typeSymbol.MetadataName;

                string ns = typeSymbol.ContainingNamespace?.ToString();
                if (!string.IsNullOrEmpty(ns))
                    return ns + "." + typeSymbol.MetadataName;
                return typeSymbol.MetadataName;
            }
        }

        /// <summary>
        /// 以更友好的方式返回类型的显示字符串，正确处理数组和类型参数（泛型参数始终保留原名）。
        /// 对于数组类型，会递归处理元素类型并附加秩声明。
        /// </summary>
        /// <param name="format">符号显示格式；若为 <see langword="null"/>，则使用 <see cref="SymbolDisplayFormat.FullyQualifiedFormat"/>。</param>
        /// <returns>经过优化的类型显示字符串。</returns>
        public string ToDisplayStringBetter(SymbolDisplayFormat format = null)
        {
            format ??= SymbolDisplayFormat.FullyQualifiedFormat;

            //类型参数（泛型参数）总是保留原名
            if (typeSymbol is ITypeParameterSymbol)
                return typeSymbol.ToDisplayString(format);

            if (typeSymbol is IArrayTypeSymbol arrayTypeSymbol)
            {
                string elementName = arrayTypeSymbol.ElementType.ToDisplayStringBetter(format); //递归处理内层名

                //根据秩生成方括号部分
                int rank = arrayTypeSymbol.Rank;
                string brackets = rank == 1 ? "[]" : "[" + new string(',', rank - 1) + "]";

                return elementName + brackets;
            }

            return typeSymbol.ToDisplayString(format);
        }

        /// <summary>
        /// 生成类型的显示字符串，若非公共访问级别则替换为 <c>"object"</c>。
        /// 适用于需要保证生成代码中不暴露非公开类型的场景。
        /// </summary>
        /// <param name="format">符号显示格式。</param>
        /// <param name="nonPublic">输出参数，指示该类型是否为非公共访问级别。</param>
        /// <returns>如果类型是公共的，返回其优化显示字符串；否则返回 <c>"object"</c>。</returns>
        public string ToDisplayStringWithObjectForNonPublic(SymbolDisplayFormat format, out bool nonPublic)
        {
            //检查访问性，非 public 替换为 object
            if (!typeSymbol.IsPubliclyAccessible)
            {
                nonPublic = true;
                return "object";
            }

            nonPublic = false;
            return typeSymbol.ToDisplayStringBetter(format);
        }

        /// <summary>
        /// 递归判断一个类型符号在完整可访问性意义上是否相当于 <c>public</c>。
        /// </summary>
        /// <returns>
        /// 若类型（及其所有构成部分）完全可公开访问，则返回 <see langword="true"/>；
        /// 否则返回 <see langword="false"/>。<paramref name="typeSymbol"/> 为 <see langword="null"/> 时也返回 <see langword="false"/>。
        /// </returns>
        /// <remarks>
        /// <para>此方法采用如下递归规则进行判定：</para>
        /// <list type="bullet">
        /// <item/><description/><b>数组类型</b>（任意维度和交错嵌套）：检查其元素类型的可访问性，例如 <c>int[][,]</c> 会递归到 <see cref="int"/>。
        /// <item/><description/><b>指针类型</b>：检查指向的目标类型的可访问性。
        /// <item/><description/><b>函数指针类型</b>：当前实现一律视为可公开访问。
        /// <item/><description/><b>动态类型</b>（<c>dynamic</c>）：始终视为可公开访问。
        /// <item/><description/><b>命名类型</b>（含泛型构造类型）：首先要求类型自身的 <see cref="INamedTypeSymbol.DeclaredAccessibility"/> 为 <see cref="Accessibility.Public"/>，然后递归要求其所有类型实参（<see cref="INamedTypeSymbol.TypeArguments"/>）均可公开访问。
        /// <br/>若任何类型实参为内部类型，则整体不可访问。
        /// <item/><description/><b>其他类型</b>：回退到使用 <see cref="ISymbol.DeclaredAccessibility"/> 与 <see cref="Accessibility.Public"/> 比较。
        /// </list>
        /// <para>该方法适用于分析器需要判断类型（例如方法参数、字段或属性类型）
        /// 能否在程序集外部安全暴露的场景。</para>
        /// </remarks>
        /// <example>
        /// <code>
        /// // int[] -> true (int is public)
        /// bool result1 = IsPubliclyAccessible(arrayOfIntType);
        /// 
        /// // List&lt;InternalClass&gt; -> false (type argument is internal)
        /// bool result2 = IsPubliclyAccessible(listOfInternalType);
        /// </code>
        /// </example>
        public bool IsPubliclyAccessible
        {
            get
            {
                if (typeSymbol is null)
                    return false;

                switch (typeSymbol.TypeKind)
                {
                    case TypeKind.TypeParameter:
                        return true;
                    case TypeKind.Array: //数组：检查元素类型
                        return ((IArrayTypeSymbol)typeSymbol).ElementType.IsPubliclyAccessible;
                    case TypeKind.Dynamic: //dynamic 总是视为 public
                        return true;
                    case TypeKind.Pointer: //指针类型：检查指向的类型
                        return ((IPointerTypeSymbol)typeSymbol).PointedAtType.IsPubliclyAccessible;
                    case TypeKind.FunctionPointer: //函数指针简化处理为 public（可按需扩展）
                        return true;
                    default:
                        // 对于命名类型（包括泛型和非泛型）
                        if (typeSymbol is INamedTypeSymbol namedType)
                        {
                            if (namedType.IsUnboundGenericType) //未绑定泛型参数直接返回 true
                                return true;

                            if (namedType.DeclaredAccessibility != Accessibility.Public) //类型本身
                                return false;

                            foreach (ITypeSymbol typeArg in namedType.TypeArguments) //类型实参
                            {
                                if (!typeArg.IsPubliclyAccessible)
                                    return false;
                            }

                            return true;
                        }

                        //其他类型回退到 DeclaredAccessibility
                        return typeSymbol.DeclaredAccessibility == Accessibility.Public;
                }
            }
        }
    }

    /// <summary>
    /// 为 <see cref="string"/> 提供与代码生成相关的扩展功能。
    /// </summary>
    extension(string text)
    {
        /// <summary>
        /// 为多行文本的每一行添加指定级别的缩进（每级缩进 4 个空格）。
        /// 空行不会添加缩进。
        /// </summary>
        /// <param name="indentLevel">缩进级别，从 0 开始。</param>
        /// <returns>添加缩进后的整个文本。</returns>
        public string AddIndent(int indentLevel)
        {
            const int indentSize = 4;

            string[] lines = text.Split('\n');
            if (lines.Length == 0)
                return text;

            string indent = new(' ', indentLevel * indentSize);

            for (int i = 0; i < lines.Length; i++)
            {
                //仅当该行不是空字符串时才添加缩进
                if (!string.IsNullOrEmpty(lines[i]))
                    lines[i] = indent + lines[i];
            }

            return string.Join("\n", lines);
        }

        /// <summary>
        /// 判断当前字符串是否为有效的 C# 标识符（以字母或下划线开头，后续可包含字母、数字或下划线）。
        /// </summary>
        public bool IsValidCSharpIdentifier
        {
            get
            {
                if (string.IsNullOrEmpty(text))
                    return false;

                //第一个字符：字母或下划线
                if (text[0] != '_' && !char.IsLetter(text[0]))
                    return false;

                //后续字符：字母、数字或下划线
                for (int i = 1; i < text.Length; i++)
                {
                    char c = text[i];
                    if (c == '_' || char.IsLetterOrDigit(c))
                        continue;
                    return false;
                }

                return true;
            }
        }
    }
    #endregion 扩展
}