// Designed by ColdsUx

namespace TransoceanicCodeAssist.SourceGenerators;

[Generator]
public class PublicizerGenerator : IIncrementalGenerator
{
    private sealed class PublicizerTypeSymbolInfo : TypeSymbolInfoBase
    {
        public const string AttributeFullName = SourceGeneratorHelper.ExternalAttributePrefix + "PublicizeAttribute";

        public INamedTypeSymbol TargetTypeSymbol { get; }
        public List<IFieldSymbol> InstanceFieldSymbols { get; }
        public List<IPropertySymbol> InstancePropertySymbols { get; }
        public List<IMethodSymbol> InstanceMethodSymbols { get; }
        public List<IFieldSymbol> StaticFieldSymbols { get; }
        public List<IPropertySymbol> StaticPropertySymbols { get; }
        public List<IMethodSymbol> StaticMethodSymbols { get; }

        public PublicizerTypeSymbolInfo(INamedTypeSymbol symbol, Compilation compilation) : base(symbol)
        {
            if (!Valid)
                return;

            if (!TryGetAttribute(AttributeFullName, out AttributeData attributeData) || attributeData.ConstructorArguments.Length != 1)
            {
                Valid = false;
                return;
            }

            TypedConstant targetTypeArg = attributeData.ConstructorArguments[0];
            if (targetTypeArg.Kind != TypedConstantKind.Type)
            {
                Valid = false;
                return;
            }

            ITypeSymbol targetTypeFromAttr = (ITypeSymbol)targetTypeArg.Value;
            if (targetTypeFromAttr is null)
            {
                Valid = false;
                return;
            }

            //重新获取类型

            string fullName = targetTypeFromAttr.FullMetadataName;
            INamedTypeSymbol targetType = compilation.GetTypeByMetadataName(fullName);

            TargetTypeSymbol = targetType;

            InstanceFieldSymbols = [];
            InstancePropertySymbols = [];
            InstanceMethodSymbols = [];
            StaticFieldSymbols = [];
            StaticPropertySymbols = [];
            StaticMethodSymbols = [];

            //收集成员信息

            ImmutableArray<ISymbol> memberSymbols = TargetTypeSymbol.GetMembers();

            foreach (ISymbol memberSymbol in memberSymbols)
            {
                // 记录被跳过的成员
                if (memberSymbol.IsImplicitlyDeclared
                    || memberSymbol.DeclaredAccessibility == Accessibility.Public
                    || memberSymbol.IsExtern
                    || !memberSymbol.Name.IsValidCSharpIdentifier)
                {
                    continue;
                }

                switch (memberSymbol)
                {
                    case IFieldSymbol fieldSymbol:
                        if (fieldSymbol.IsStatic)
                        {
                            StaticFieldSymbols.Add(fieldSymbol);
                        }
                        else
                        {
                            InstanceFieldSymbols.Add(fieldSymbol);
                        }
                        break;
                    case IPropertySymbol propertySymbol:
                        if (propertySymbol.IsStatic)
                        {
                            StaticPropertySymbols.Add(propertySymbol);
                        }
                        else
                        {
                            InstancePropertySymbols.Add(propertySymbol);
                        }
                        break;
                    case IMethodSymbol methodSymbol when methodSymbol.MethodKind == MethodKind.Ordinary:
                        if (methodSymbol.IsStatic)
                        {
                            StaticMethodSymbols.Add(methodSymbol);
                        }
                        else
                        {
                            InstanceMethodSymbols.Add(methodSymbol);
                        }
                        break;
                    default:
                        break;
                }
            }
        }
    }

    private const string HelperMethodClass = "global::Transoceanic.Framework.Helpers.AbstractionHandlers.PublicizerHandler.";
    private const string ReflectionNamespace = "global::System.Reflection.";

    private const string TargetTypeFieldName = "c_TargetType";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<PublicizerTypeSymbolInfo>> c = SourceGeneratorHelper.GetCollectedTypeInfos(context, (s, complition) => new PublicizerTypeSymbolInfo(s, complition));
        context.RegisterSourceOutput(c, RegisterAction);
    }

    private static void RegisterAction(SourceProductionContext spc, ImmutableArray<PublicizerTypeSymbolInfo> source)
    {
        string fileName = "Publicizer.g.cs";

        StringBuilder builder = new();

        builder.AppendLine("""
            // <auto-generated/>

            // Generated Publicizer
            // Designed by ColdsUx

            #pragma warning disable CS0106
            #pragma warning disable CS0109
            #pragma warning disable CS1591

            """);

        for (int i = 0; i < source.Length; i++)
        {
            PublicizerTypeSymbolInfo typeInfo = source[i];
            if (i > 0)
                builder.AppendLine();
            builder.AppendLine(RegisterType(typeInfo));
        }

        spc.AddSource(fileName, builder.ToString());
    }

    private static string RegisterType(PublicizerTypeSymbolInfo typeInfo)
    {
        StringBuilder builder = new();

        string targetTypeName = typeInfo.TargetTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        builder.AppendLine($$"""
            {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
            public static new readonly global::System.Type {{TargetTypeFieldName}} = typeof({{targetTypeName}});
            """);

        builder.AppendLine(HandleInstanceFields(typeInfo));
        builder.AppendLine(HandleInstanceProperties(typeInfo));
        builder.AppendLine(HandleInstanceMethods(typeInfo));
        builder.AppendLine(HandleStaticFields(typeInfo));
        builder.AppendLine(HandleStaticProperties(typeInfo));
        builder.AppendLine(HandleStaticMethods(typeInfo));

        return typeInfo.GenerateDeclarationText(builder.ToString(), 0, true);
    }

    private static string HandleInstanceFields(PublicizerTypeSymbolInfo typeInfo)
    {
        if (typeInfo.InstanceFieldSymbols.Count <= 0)
            return "\n// NO Instance Fields";

        StringBuilder typeBuilder = new();

        typeBuilder.AppendLine("""

            #region Instance Fields
            """);

        bool first = true;

        foreach (IFieldSymbol fieldSymbol in typeInfo.InstanceFieldSymbols)
        {
            StringBuilder localBuilder = new();

            if (first)
                first = false;
            else
                localBuilder.AppendLine();

            string name = fieldSymbol.Name;
            string typeName = fieldSymbol.Type.ToDisplayStringWithObjectForNonPublic(SymbolDisplayFormat.FullyQualifiedFormat, out bool nonPublic);
            string nonPublicIndicator = nonPublic ? " (non-public type)" : "";
            string fieldInfoName = $"i_f_{name}";

            bool hasSetter = !fieldSymbol.IsConst && !fieldSymbol.IsReadOnly;
            string setter = hasSetter ? $"set => {fieldInfoName}.SetValue(base.Source, value);" : "// no setter";

            localBuilder.Append($$"""
                // {{name}}{{nonPublicIndicator}}
                {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                public static readonly {{ReflectionNamespace}}FieldInfo {{fieldInfoName}} = {{HelperMethodClass}}GetInstanceField({{TargetTypeFieldName}}, "{{name}}");
                public {{typeName}} {{name}}
                {
                    get => ({{typeName}}){{fieldInfoName}}.GetValue(base.Source);
                    {{setter}}
                }
                """);

            typeBuilder.AppendLine(localBuilder.ToString());
        }

        typeBuilder.Append("#endregion Instance Fields");

        return typeBuilder.ToString();
    }

    private static string HandleInstanceProperties(PublicizerTypeSymbolInfo typeInfo)
    {
        if (typeInfo.InstancePropertySymbols.Count <= 0)
            return "\n// NO Instance Properties";

        StringBuilder typeBuilder = new();

        typeBuilder.AppendLine("""

        #region Instance Properties
        """);

        bool first = true;

        foreach (IPropertySymbol propertySymbol in typeInfo.InstancePropertySymbols)
        {
            if (propertySymbol.IsIndexer)
                continue;

            StringBuilder localBuilder = new();

            if (first)
                first = false;
            else
                localBuilder.AppendLine();

            string name = propertySymbol.Name;
            string typeName = propertySymbol.Type.ToDisplayStringWithObjectForNonPublic(SymbolDisplayFormat.FullyQualifiedFormat, out bool nonPublic);
            string nonPublicIndicator = nonPublic ? " (non-public type)" : "";
            string propertyInfoName = $"i_p_{name}";

            bool hasGetter = propertySymbol.GetMethod is not null;
            bool hasSetter = propertySymbol.SetMethod is not null;

            if (!hasGetter && !hasSetter) //一般不应出现既没有getter又没有setter的情况
                continue;

            string getter = hasGetter ? $$"""get => ({{typeName}}){{propertyInfoName}}.GetValue(base.Source);""" : "// no getter";
            string setter = hasSetter ? $$"""set => {{propertyInfoName}}.SetValue(base.Source, value);""" : "// no setter";

            localBuilder.Append($$"""
                // {{name}}{{nonPublicIndicator}}
                {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                public static readonly {{ReflectionNamespace}}PropertyInfo {{propertyInfoName}} = {{HelperMethodClass}}GetInstanceProperty({{TargetTypeFieldName}}, {{"\"" + name + "\""}});
                public {{typeName}} {{name}}
                {
                    {{getter}}
                    {{setter}}
                }
                """);

            typeBuilder.AppendLine(localBuilder.ToString());
        }

        typeBuilder.Append("#endregion Instance Properties");

        return typeBuilder.ToString();
    }

    private static string HandleInstanceMethods(PublicizerTypeSymbolInfo typeInfo)
    {
        if (typeInfo.InstanceMethodSymbols.Count == 0)
            return "\n// NO Instance Methods";

        StringBuilder typeBuilder = new();

        typeBuilder.AppendLine("""

        #region Instance Methods
        """);

        bool first = true;

        foreach (IMethodSymbol methodSymbol in typeInfo.InstanceMethodSymbols)
        {
            StringBuilder localBuilder = new();

            if (first)
                first = false;
            else
                localBuilder.AppendLine();

            string name = methodSymbol.Name;

            if (methodSymbol.Parameters.Any(p => p.Type.DeclaredAccessibility != Accessibility.Public))
            {
                localBuilder.Append($$"""
                    // {{name}}
                    // Not supported due to having non-public parameter types
                    """);
            }
            else if (methodSymbol.IsGenericMethod)
            {
                localBuilder.Append($$"""
                    // {{name}}
                    // Not supported due to having generic type parameters
                    """);
            }
            else
            {
                List<string> paramTypeNames = [..
                from IParameterSymbol param in methodSymbol.Parameters
                let typeName = param.Type.Name
                    .Replace(".", "_")
                    .Replace("<", "_")
                    .Replace(">", "_")
                    .Replace(",", "_")
                    .Replace(" ", "")
                    + (param.RefKind != RefKind.None ? "ByRef" : "")
                select typeName];
                string suffix = name + (paramTypeNames.Count > 0 ? "_" + string.Join("_", paramTypeNames) : "");

                string methodInfoFieldName = $"i_m_{suffix}";
                string paramTypesArray = string.Join(", ", methodSymbol.Parameters.Select(p => $"typeof({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})" + (p.RefKind != RefKind.None ? ".MakeByRefType()" : "")));
                string delegateTypeName = $"Orig_{suffix}";
                string delegateFieldName = $"i_d_{suffix}";

                MethodSymbolInfoBase methodSymbolInfo = new(methodSymbol);

                string[] parameterNames = [$"({typeInfo.TargetTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})base.Source", .. methodSymbolInfo.ParameterNamesForCall];
                localBuilder.Append($$"""
                    // {{name}}
                    {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                    public static readonly {{ReflectionNamespace}}MethodInfo {{methodInfoFieldName}} = {{HelperMethodClass}}GetInstanceMethod({{TargetTypeFieldName}}, "{{name}}", new global::System.Type[] {{{(string.IsNullOrEmpty(paramTypesArray) ? " " : $" {paramTypesArray} ")}}});
                    {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                    {{methodSymbolInfo.GenerateDelegateDeclaration(delegateTypeName)}}
                    {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                    public static readonly {{delegateTypeName}} {{delegateFieldName}} = {{methodInfoFieldName}}.CreateDelegate<{{delegateTypeName}}>();
                    public {{methodSymbolInfo.ReturnTypeString}} {{name}}({{string.Join(", ", methodSymbolInfo.ParameterDeclarationsWithObjectForNonPublic)}}) => {{delegateFieldName}}.Invoke({{string.Join(", ", parameterNames)}});
                    """);
            }

            typeBuilder.AppendLine(localBuilder.ToString());
        }

        typeBuilder.Append("#endregion Instance Methods");

        return typeBuilder.ToString();
    }

    private static string HandleStaticFields(PublicizerTypeSymbolInfo typeInfo)
    {
        if (typeInfo.StaticFieldSymbols.Count <= 0)
            return "\n// NO Static Fields";

        StringBuilder typeBuilder = new();

        typeBuilder.AppendLine("""

        #region Static Fields
        """);

        bool first = true;

        foreach (IFieldSymbol fieldSymbol in typeInfo.StaticFieldSymbols)
        {
            StringBuilder localBuilder = new();

            if (first)
                first = false;
            else
                localBuilder.AppendLine();

            string name = fieldSymbol.Name;
            string typeName = fieldSymbol.Type.ToDisplayStringWithObjectForNonPublic(SymbolDisplayFormat.FullyQualifiedFormat, out bool nonPublic);
            string nonPublicIndicator = nonPublic ? " (non-public type)" : "";
            string fieldInfoName = $"s_f_{name}";

            bool hasSetter = !fieldSymbol.IsConst && !fieldSymbol.IsReadOnly;
            string setter = hasSetter ? $"set => {fieldInfoName}.SetValue(null, value);" : "// no setter";

            localBuilder.Append($$"""
                // {{name}}{{nonPublicIndicator}}
                {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                public static readonly {{ReflectionNamespace}}FieldInfo {{fieldInfoName}} = {{HelperMethodClass}}GetStaticField({{TargetTypeFieldName}}, {{"\"" + name + "\""}});
                public static {{typeName}} {{name}}
                {
                    get => ({{typeName}}){{fieldInfoName}}.GetValue(null);
                    {{setter}}
                }
                """);

            typeBuilder.AppendLine(localBuilder.ToString());
        }

        typeBuilder.Append("#endregion Static Fields");

        return typeBuilder.ToString();
    }

    private static string HandleStaticProperties(PublicizerTypeSymbolInfo typeInfo)
    {
        if (typeInfo.StaticPropertySymbols.Count <= 0)
            return "\n// NO Static Properties";

        StringBuilder typeBuilder = new();

        typeBuilder.AppendLine("""

        #region Static Properties
        """);

        bool first = true;

        foreach (IPropertySymbol propertySymbol in typeInfo.StaticPropertySymbols)
        {
            if (propertySymbol.IsIndexer)
                continue;

            StringBuilder localBuilder = new();

            if (first)
                first = false;
            else
                localBuilder.AppendLine();

            string name = propertySymbol.Name;
            string typeName = propertySymbol.Type.ToDisplayStringWithObjectForNonPublic(SymbolDisplayFormat.FullyQualifiedFormat, out bool nonPublic);
            string nonPublicIndicator = nonPublic ? " (non-public type)" : "";
            string propertyInfoName = $"s_p_{name}";

            bool hasGetter = propertySymbol.GetMethod is not null;
            bool hasSetter = propertySymbol.SetMethod is not null;

            if (!hasGetter && !hasSetter) // 一般不应出现既没有 getter 又没有 setter 的情况
                continue;

            string getter = hasGetter ? $$"""get => ({{typeName}}){{propertyInfoName}}.GetValue(null);""" : "// no getter";
            string setter = hasSetter ? $$"""set => {{propertyInfoName}}.SetValue(null, value);""" : "// no setter";

            localBuilder.Append($$"""
                // {{name}}{{nonPublicIndicator}}
                {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                public static readonly {{ReflectionNamespace}}PropertyInfo {{propertyInfoName}} = {{HelperMethodClass}}GetStaticProperty({{TargetTypeFieldName}}, {{"\"" + name + "\""}});
                public static {{typeName}} {{name}}
                {
                    {{getter}}
                    {{setter}}
                }
                """);

            typeBuilder.AppendLine(localBuilder.ToString());
        }

        typeBuilder.Append("#endregion Static Properties");

        return typeBuilder.ToString();
    }

    private static string HandleStaticMethods(PublicizerTypeSymbolInfo typeInfo)
    {
        if (typeInfo.StaticMethodSymbols.Count == 0)
            return "\n// NO Static Methods";

        StringBuilder typeBuilder = new();

        typeBuilder.AppendLine("""

        #region Static Methods
        """);

        bool first = true;

        foreach (IMethodSymbol methodSymbol in typeInfo.StaticMethodSymbols)
        {
            StringBuilder localBuilder = new();

            if (first)
                first = false;
            else
                localBuilder.AppendLine();

            string name = methodSymbol.Name;

            if (methodSymbol.Parameters.Any(p => p.Type.DeclaredAccessibility != Accessibility.Public))
            {
                localBuilder.Append($$"""
                    // {{name}}
                    // Not supported due to having non-public parameter types
                    """);
            }
            else if (methodSymbol.IsGenericMethod)
            {
                localBuilder.Append($$"""
                    // {{name}}
                    // Not supported due to having generic type parameters
                    """);
            }
            else
            {
                List<string> paramTypeNames = [..
                from IParameterSymbol param in methodSymbol.Parameters
                let typeName = param.Type.Name
                    .Replace(".", "_")
                    .Replace("<", "_")
                    .Replace(">", "_")
                    .Replace(",", "_")
                    .Replace(" ", "")
                    + (param.RefKind != RefKind.None ? "ByRef" : "")
                select typeName];
                string suffix = name + (paramTypeNames.Count > 0 ? "_" + string.Join("_", paramTypeNames) : "");

                string methodInfoFieldName = $"s_m_{suffix}";
                string paramTypesArray = string.Join(", ", methodSymbol.Parameters.Select(p => $"typeof({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})" + (p.RefKind != RefKind.None ? ".MakeByRefType()" : "")));
                string delegateTypeName = $"Orig_{suffix}";
                string delegateFieldName = $"s_d_{suffix}";

                MethodSymbolInfoBase methodSymbolInfo = new(methodSymbol);

                localBuilder.Append($$"""
                    // {{name}}
                    {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                    public static readonly {{ReflectionNamespace}}MethodInfo {{methodInfoFieldName}} = {{HelperMethodClass}}GetStaticMethod({{TargetTypeFieldName}}, "{{name}}", new global::System.Type[] {{{(string.IsNullOrEmpty(paramTypesArray) ? " " : $" {paramTypesArray} ")}}});
                    {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                    {{methodSymbolInfo.GenerateDelegateDeclaration(delegateTypeName)}}
                    {{SourceGeneratorHelper.NeverBrowsableIdentifier}}
                    public static readonly {{delegateTypeName}} {{delegateFieldName}} = {{methodInfoFieldName}}.CreateDelegate<{{delegateTypeName}}>();
                    public static {{methodSymbolInfo.ReturnTypeString}} {{name}}({{string.Join(", ", methodSymbolInfo.ParameterDeclarationsWithObjectForNonPublic)}}) => {{delegateFieldName}}.Invoke({{string.Join(", ", methodSymbolInfo.ParameterNamesForCall)}});
                    """);
            }

            typeBuilder.AppendLine(localBuilder.ToString());
        }

        typeBuilder.Append("#endregion Static Methods");

        return typeBuilder.ToString();
    }
}